/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Task = IDL.Record({
  'reward' : IDL.Opt(IDL.Nat),
  'title' : IDL.Text,
  'description' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'upi' : IDL.Text, 'name' : IDL.Text });
export const Time = IDL.Int;
export const ReferralLink = IDL.Record({
  'title' : IDL.Text,
  'created' : Time,
  'commission' : IDL.Opt(IDL.Nat),
  'destinationUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)], [], []),
  'approvePayoutRequest' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createReferralLink' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'getAvailableTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getReferralLinks' : IDL.Func([], [IDL.Vec(ReferralLink)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rejectPayoutRequest' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'requestPayout' : IDL.Func([IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'trackReferralClick' : IDL.Func([IDL.Principal, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Task = IDL.Record({
    'reward' : IDL.Opt(IDL.Nat),
    'title' : IDL.Text,
    'description' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'upi' : IDL.Text, 'name' : IDL.Text });
  const Time = IDL.Int;
  const ReferralLink = IDL.Record({
    'title' : IDL.Text,
    'created' : Time,
    'commission' : IDL.Opt(IDL.Nat),
    'destinationUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addTask' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)], [], []),
    'approvePayoutRequest' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createReferralLink' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'getAvailableTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getBalance' : IDL.Func([], [IDL.Nat], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getReferralLinks' : IDL.Func([], [IDL.Vec(ReferralLink)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rejectPayoutRequest' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'requestPayout' : IDL.Func([IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'trackReferralClick' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };