/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface PayoutRequest {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'approved' : null } |
    { 'rejected' : null },
  'created' : Time,
  'amount' : bigint,
}
export interface ReferralLink {
  'title' : string,
  'created' : Time,
  'commission' : [] | [bigint],
  'destinationUrl' : string,
}
export interface Task {
  'reward' : [] | [bigint],
  'title' : string,
  'description' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'upi' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addTask' : ActorMethod<[string, string, [] | [bigint]], undefined>,
  'approvePayoutRequest' : ActorMethod<[Principal, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bulkAddTasks' : ActorMethod<[Array<Task>], undefined>,
  'createReferralLink' : ActorMethod<
    [string, string, [] | [bigint]],
    undefined
  >,
  'getAllPayoutRequests' : ActorMethod<
    [],
    Array<[Principal, Array<PayoutRequest>]>
  >,
  'getAvailableTasks' : ActorMethod<[], Array<Task>>,
  'getBalance' : ActorMethod<[], bigint>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyPayoutRequests' : ActorMethod<[], [] | [Array<PayoutRequest>]>,
  'getReferralLinks' : ActorMethod<[], Array<ReferralLink>>,
  'getUserPayoutRequests' : ActorMethod<
    [Principal],
    [] | [Array<PayoutRequest>]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isAdmin' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'rejectPayoutRequest' : ActorMethod<[Principal, bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'requestPayout' : ActorMethod<[bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'trackReferralClick' : ActorMethod<[Principal, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];